ci: Update Dockerfile and devcontainer.json to add Zsh and related tools support, and add README.md

diff --git a/src/base/.devcontainer/Dockerfile b/src/base/.devcontainer/Dockerfile
--- a/src/base/.devcontainer/Dockerfile
+++ b/src/base/.devcontainer/Dockerfile
@@ -1,2 +1,18 @@
-ARG VARIANT="ubuntu"
-FROM mcr.microsoft.com/devcontainers/base:${VARIANT}
+ARG VARIANT="noble"
+FROM buildpack-deps:${VARIANT}-curl
+
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
+        if id "ubuntu" &>/dev/null; then \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        else \
+            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        fi; \
+    fi
+
+# [Optional] Uncomment this section to install additional OS packages.
+# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+#     && apt-get -y install --no-install-recommends <your-package-list-here>
+
+# Fix locale issues https://github.com/devcontainers/features/issues/664
+ENV LANG=en_US.UTF-8
